/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import Bean.BatchBean;
import Bean.DatabaseManager;
import Bean.DepartmentBean;
import Bean.FacultyBean;
import Bean.PartBean;
import Bean.ProgramBean;
import Bean.SeatListDetailBean;
import Bean.StudentPartBean;
import Bean.StudentsBean;
import javax.swing.JOptionPane;

/**
 *
 * @author Isra Khan
 */
public class StudentPartFrame extends javax.swing.JFrame {

    /**
     * Creates new form StudentPartFrame
     */
    public StudentPartFrame() {
        initComponents();
       
        getFaculty();
    }
    
    
      private void getFaculty(){
        try{
            java.util.Vector v=DatabaseManager.getFaculty();
            FacComboBox.removeAllItems();
                for(int i=0; i<v.size(); i++){
               FacComboBox.addItem(v.elementAt(i));
                
                }
            
        }//try
        catch(Exception e){
        
            e.printStackTrace();
        }
    
    }
       
       
       
       
       
       
       
      
      private void getDepartments(){
 FacultyBean bean=(FacultyBean)FacComboBox.getSelectedItem();
 if(bean==null) return;
 try{
 java.util.Vector v=DatabaseManager.getDepartment(bean.getFacId());
 DepartmentComboBox.removeAllItems();
 for(int i=0; i<v.size(); i++){
     DepartmentComboBox.addItem(v.elementAt(i));
 }
 } catch(Exception e){e.printStackTrace();}
 
 }
      
      private void getPrograms(){
      DepartmentBean bean= (DepartmentBean)DepartmentComboBox.getSelectedItem();
        if(bean==null)return;
            try{
           java.util.Vector v=DatabaseManager.getProgram(bean.getDeptId());
           ProgComboBox.removeAllItems();
            for(int i=0; i<v.size(); i++){
            
            ProgComboBox.addItem(v.elementAt(i));
            }
            }catch(Exception e){
                    e.printStackTrace();
            }
      }
      
      private void getBatchYears(){
   ProgramBean bean=(ProgramBean) ProgComboBox.getSelectedItem();
    if(bean==null) return;
        try{
        java.util.Vector v=DatabaseManager.getBatch(bean.getProgId());
        BatchYearComboBox.removeAllItems();
        for(int i=0; i<v.size(); i++){
        BatchYearComboBox.addItem(v.elementAt(i));
        }
        
        }catch(Exception e){e.printStackTrace();}
   }//getbatchyears
    
      
      
      
        private void getShiftAndGroup(){
   BatchBean bean=(BatchBean)BatchYearComboBox.getSelectedItem();
    if(bean==null) return;
    
    this.ShiftTextField.setText(bean.getShift());
    this.GroupTextField.setText(bean.getGroupDesc());
    
    
        }
  
        
        
      private void getPart(){
       BatchBean bean=(BatchBean)BatchYearComboBox.getSelectedItem();
       if(bean==null)return;
        
        try{
            PartComboBox.removeAllItems();
           java.util.Vector v =DatabaseManager.getPart(bean.getBatchId());
           for(int i=0; i<v.size(); i++){
               PartComboBox.addItem(v.elementAt(i));
           
            }
        
        }
        catch(Exception e){e.printStackTrace();}
    
    }   
   
    public void pasteStudentPart(){
   PartBean bean=(PartBean)PartComboBox.getSelectedItem();
    if(bean==null)return;
        
        String remarks=RemarksTextArea.getText();
        try{
             int rows =DatabaseManager.getStudentPaste(bean.getPart(),bean.getBatchId(),remarks);
             
                getStudentPart();
                 JOptionPane.showMessageDialog(this,rows+"Record Paste Successfully");
           
        }
        catch(Exception e){e.printStackTrace();}
              
              }
    
    public void getStudentPart(){
        PartBean bean=(PartBean) PartComboBox.getSelectedItem();
        if(bean==null)return;
        
        try{
         
          java.util.Vector v = DatabaseManager.getStudentPart(bean.getBatchId(),bean.getPart());
            RollNoList.setListData(v);
            
        }
        catch(Exception e){e.printStackTrace();}
    }
    
    
    
        
    
     
 
  
  
    
    
    
    
        
        
    
    
   
    
   
  
    
    
    
    
  
    
               
    
    
 
    
        
        
        
        
        
            
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

    public void clear(){
        
  
     RemarksTextArea.setText("");
     
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        RemarksTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        RollNoList = new javax.swing.JList();
        BackButton = new javax.swing.JButton();
        AddButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        FacComboBox = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        DepartmentComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        ProgComboBox = new javax.swing.JComboBox();
        BatchYearComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        SurnameTextField = new javax.swing.JTextField();
        NameTextField = new javax.swing.JTextField();
        FNameTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ShiftTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        GroupTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        PasteButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        PartComboBox = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        RollNumberTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Student Part");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 11, 151, 29);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Remarks");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(130, 429, 60, 17);

        RemarksTextArea.setColumns(20);
        RemarksTextArea.setRows(5);
        jScrollPane1.setViewportView(RemarksTextArea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(130, 457, 290, 96);

        RollNoList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                RollNoListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(RollNoList);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(552, 58, 138, 482);

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton);
        BackButton.setBounds(550, 555, 138, 28);

        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AddButton);
        AddButton.setBounds(130, 559, 61, 28);

        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateButton);
        UpdateButton.setBounds(200, 559, 67, 28);

        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteButton);
        DeleteButton.setBounds(270, 559, 63, 28);

        ClearButton.setText("Clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ClearButton);
        ClearButton.setBounds(339, 559, 81, 28);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Faculty");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 68, 70, 17);

        FacComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        FacComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(FacComboBox);
        FacComboBox.setBounds(140, 58, 280, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Department");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 118, 90, 17);

        DepartmentComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        DepartmentComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepartmentComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(DepartmentComboBox);
        DepartmentComboBox.setBounds(140, 108, 280, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Program");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 168, 60, 17);

        ProgComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ProgComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProgComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(ProgComboBox);
        ProgComboBox.setBounds(140, 158, 280, 30);

        BatchYearComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        BatchYearComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BatchYearComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(BatchYearComboBox);
        BatchYearComboBox.setBounds(140, 220, 70, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Shift");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(230, 194, 70, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 310, 40, 17);

        SurnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SurnameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(SurnameTextField);
        SurnameTextField.setBounds(140, 389, 280, 30);

        NameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(NameTextField);
        NameTextField.setBounds(140, 309, 280, 30);

        FNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FNameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(FNameTextField);
        FNameTextField.setBounds(140, 349, 280, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Father Name");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 348, 90, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Surname");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(60, 388, 70, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Batch");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(90, 218, 40, 17);
        getContentPane().add(ShiftTextField);
        ShiftTextField.setBounds(220, 220, 70, 30);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(320, 220, 0, 0);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Group");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(360, 200, 43, 17);
        getContentPane().add(GroupTextField);
        GroupTextField.setBounds(348, 226, 72, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Roll Number");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(560, 30, 128, 22);

        PasteButton.setText("Paste");
        PasteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(PasteButton);
        PasteButton.setBounds(262, 262, 140, 41);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Parts");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(90, 268, 40, 17);

        PartComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        PartComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PartComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(PartComboBox);
        PartComboBox.setBounds(140, 262, 70, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Roll Number");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(440, 190, 85, 17);

        RollNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RollNumberTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(RollNumberTextField);
        RollNumberTextField.setBounds(427, 226, 107, 30);

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(430, 260, 100, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RollNoListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_RollNoListValueChanged

         
            StudentPartBean stdPartBean=(StudentPartBean) RollNoList.getSelectedValue();
        if(stdPartBean==null)return;
        
            
        try{
        
         StudentsBean stdBean=DatabaseManager.getStudent(stdPartBean.getRollNo());
         if(stdBean==null){
          //   javax.swing.JOptionPane.showMessageDialog(this,"Record NOT found.");
             return;
         }
         
                NameTextField.setText(stdBean.getStdName());
                FNameTextField.setText(stdBean.getFName());
                SurnameTextField.setText(stdBean.getSurname());
       
     
                        
       
               
            
        }
        catch(Exception e){e.printStackTrace();}
        
        
        
        
        
        
    }//GEN-LAST:event_RollNoListValueChanged

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        clear();
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
      hide();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void SurnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SurnameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SurnameTextFieldActionPerformed

    private void FNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FNameTextFieldActionPerformed

    private void DepartmentComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepartmentComboBoxActionPerformed
        getPrograms();
    }//GEN-LAST:event_DepartmentComboBoxActionPerformed

    private void ProgComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProgComboBoxActionPerformed
       getBatchYears();
    }//GEN-LAST:event_ProgComboBoxActionPerformed

    private void FacComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacComboBoxActionPerformed
      getDepartments();
    }//GEN-LAST:event_FacComboBoxActionPerformed

    private void PasteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasteButtonActionPerformed
            pasteStudentPart();
      
    }//GEN-LAST:event_PasteButtonActionPerformed

    private void BatchYearComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BatchYearComboBoxActionPerformed
        getPart();
        getShiftAndGroup();
    }//GEN-LAST:event_BatchYearComboBoxActionPerformed

    private void PartComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PartComboBoxActionPerformed
      
        getStudentPart();
        
        
        
        
    }//GEN-LAST:event_PartComboBoxActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
     
       Object rollnoObj[]=RollNoList.getSelectedValues();
        if(rollnoObj==null|| rollnoObj.length==0)return;
        int rows=0;
        for(int i=0; i<rollnoObj.length; i++){
         StudentPartBean bean=(StudentPartBean)rollnoObj[i];  
         if(bean==null)return;
          try{
         rows+=DatabaseManager.deleteStudentPartDetails(bean.getBatchId(),bean.getPart(),bean.getRollNo());
         
          }catch(Exception e){e.printStackTrace();}
        }
         
        
        
         JOptionPane.showMessageDialog(this,rows+"Records Deleted");
          getStudentPart();
            
        
        
        
        
        
        
        
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed

              StudentPartBean bean=(StudentPartBean)RollNoList.getSelectedValue();
      
      if(bean==null)return;
       
    
       String remarks=RemarksTextArea.getText();    
      
       
        try{
        int rows=DatabaseManager.updateStudentPart(bean.getPart(),bean.getBatchId(),bean.getRollNo(),remarks);  
            if(rows>=1){
                getStudentPart();
                clear();
                JOptionPane.showMessageDialog(this,+rows+"Data updated");
            }
        }catch(Exception e){JOptionPane.showMessageDialog(null,"ERROR"+e.getMessage());}
   
        
        
        
        
        
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
     PartBean bean=(PartBean)PartComboBox.getSelectedItem();
             
       
      
      if(bean==null)return;
       
        String rollNum=RollNumberTextField.getText();
       String remarks=RemarksTextArea.getText();    
      
       
        try{
        int rows=DatabaseManager.addStudentPart(bean.getPart(),bean.getBatchId(),rollNum,remarks);  
            if(rows>=1){
                getStudentPart();
                clear();
                JOptionPane.showMessageDialog(this,+rows+"Data Added");
            }
        }catch(Exception e){JOptionPane.showMessageDialog(null,"ERROR"+e.getMessage());
        }
   
  
      
    }//GEN-LAST:event_AddButtonActionPerformed

    private void NameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTextFieldActionPerformed

    private void RollNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RollNumberTextFieldActionPerformed

        

        
        
        
        
    }//GEN-LAST:event_RollNumberTextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                try{
        
         StudentsBean stdBean=DatabaseManager.getStudent(this.RollNumberTextField.getText());
         if(stdBean==null){
             javax.swing.JOptionPane.showMessageDialog(this,"Record NOT found.");
             return;
         }
         
                NameTextField.setText(stdBean.getStdName());
                FNameTextField.setText(stdBean.getFName());
                SurnameTextField.setText(stdBean.getSurname());
        }
        catch(Exception e){e.printStackTrace();}
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentPartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentPartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentPartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentPartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentPartFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton BackButton;
    private javax.swing.JComboBox BatchYearComboBox;
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JComboBox DepartmentComboBox;
    public javax.swing.JTextField FNameTextField;
    private javax.swing.JComboBox FacComboBox;
    private javax.swing.JTextField GroupTextField;
    public javax.swing.JTextField NameTextField;
    private javax.swing.JComboBox PartComboBox;
    private javax.swing.JButton PasteButton;
    private javax.swing.JComboBox ProgComboBox;
    private javax.swing.JTextArea RemarksTextArea;
    private javax.swing.JList RollNoList;
    private javax.swing.JTextField RollNumberTextField;
    private javax.swing.JTextField ShiftTextField;
    public javax.swing.JTextField SurnameTextField;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
